### ISSUE TITLE
ETS spectra have SMILES: NA

### ISSUE THREAD

**Issue by sneumann** [meier-rene/MassBank-data#2]
Hi, the ETS spectra (https://massbank.eu/MassBank/jsp/Result.jsp?type=rcdidx&idxtype=site&srchkey=32&sortKey=name&sortAction=1&pageNo=1&exec=) , not yet here in MassBank-data,
have `SMILES: NA` instead of `SMILES: N/A`.

Once we have ETS spectra here, use `sed` to mass-convert/fix 'em,
and close this issue. Shows how cool CI for MassBank ist.

Yours, Steffen

**Comment by meier-rene** [comment]
Fixed.
